const SET_NAME = 'SET_NAME';
const SET_TYPE = 'SET_TYPE';
const SET_YEAR_START = 'SET_YEAR_START';
const SET_YEAR_END = 'SET_YEAR_END';
const SET_RATE_START = 'SET_RATE_START';
const SET_RATE_END = 'SET_RATE_END';
const SET_RATE_PROVIDER = 'SET_RATE_PROVIDER';
const SET_MOVIE_LIMIT = 'SET_MOVIE_LIMIT';
const SET_PAGE = 'SET_PAGE';
const FETCH_DATA = 'FETCH_DATA';
const FETCHED_SUCCESSEFULLY = 'FETCHED_SUCCESSEFULLY';
const FETCHING_FAILED = 'FETCHING_FAILED';

export {SET_NAME,SET_TYPE,SET_YEAR_START,SET_YEAR_END,SET_RATE_START,SET_RATE_END,SET_RATE_PROVIDER,SET_MOVIE_LIMIT,SET_PAGE,FETCHED_SUCCESSEFULLY,FETCH_DATA,FETCHING_FAILED}